/**
 * Where artifact bytes live. Keys are opaque, generated by the caller (`ws/<workspaceId>/<id>`),
 * never derived from user-supplied names; both stores reject keys that could escape their root.
 */
import { createReadStream } from "node:fs";
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve, sep } from "node:path";
import { Readable } from "node:stream";
import { BadRequestError, NetworkError, NotFoundError } from "@flowaid/workflow-core";
import { encodePath, presignUrl, sha256Hex, signRequest, type SigningKeys } from "./sigv4.js";

export type StorageKind = "local" | "s3";

export interface StoredObject {
  body: ReadableStream<Uint8Array>;
  size: number;
}

export interface PresignOptions {
  expiresSeconds: number;
  /** Sets `response-content-disposition` on the signed URL. */
  contentDisposition?: string;
  /** Sets `response-content-type` on the signed URL. */
  contentType?: string;
}

export interface ArtifactStore {
  /** The value recorded in `artifacts.storage`. */
  readonly kind: StorageKind;
  put(key: string, bytes: Uint8Array, mimeType: string): Promise<void>;
  get(key: string): Promise<Uint8Array>;
  /** Streams an object; throws NotFoundError when it is missing. */
  open(key: string): Promise<StoredObject>;
  /** A time-limited URL a client can fetch directly, or null when the store has none (local). */
  presign(key: string, opts: PresignOptions): string | null;
  delete(key: string): Promise<void>;
}

const KEY = /^[A-Za-z0-9][A-Za-z0-9._-]*(\/[A-Za-z0-9][A-Za-z0-9._-]*)*$/;

function checkKey(key: string): string {
  if (!KEY.test(key) || key.length > 1024 || key.split("/").includes(".."))
    throw new BadRequestError("invalid storage key");
  return key;
}

/** Files under one directory (`<data>/artifacts`), owner-only permissions. */
export class LocalArtifactStore implements ArtifactStore {
  readonly kind = "local" as const;
  private readonly root: string;

  constructor(root: string) {
    this.root = resolve(root);
  }

  private path(key: string): string {
    const p = resolve(join(this.root, checkKey(key)));
    if (!p.startsWith(this.root + sep)) throw new BadRequestError("invalid storage key");
    return p;
  }

  async put(key: string, bytes: Uint8Array): Promise<void> {
    const p = this.path(key);
    await mkdir(dirname(p), { recursive: true, mode: 0o700 });
    await writeFile(p, bytes, { mode: 0o600 });
  }

  async get(key: string): Promise<Uint8Array> {
    try {
      return new Uint8Array(await readFile(this.path(key)));
    } catch (error) {
      throw notFound(error, key);
    }
  }

  async open(key: string): Promise<StoredObject> {
    const p = this.path(key);
    try {
      const { size } = await stat(p);
      return {
        body: Readable.toWeb(createReadStream(p)) as ReadableStream<Uint8Array>,
        size,
      };
    } catch (error) {
      throw notFound(error, key);
    }
  }

  presign(): null {
    return null;
  }

  async delete(key: string): Promise<void> {
    await rm(this.path(key), { force: true });
  }
}

function notFound(error: unknown, key: string): unknown {
  return (error as { code?: string }).code === "ENOENT"
    ? new NotFoundError(`object ${key} not found`)
    : error;
}

export interface S3Options {
  endpoint: string;
  bucket: string;
  accessKey: string;
  secretKey: string;
  region: string;
  /** `endpoint/bucket/key` (most self-hosted stores) rather than `bucket.endpoint/key`. */
  forcePathStyle: boolean;
  /** Defaults to global fetch; tests and proxies pass their own. */
  fetch?: typeof fetch;
  /** Per-request timeout (default 60 s). */
  timeoutMs?: number;
}

/** Any S3-compatible object store, spoken to directly with SigV4-signed fetch calls. */
export class S3ArtifactStore implements ArtifactStore {
  readonly kind = "s3" as const;
  private readonly keys: SigningKeys;
  private readonly fetch: typeof fetch;

  constructor(private readonly opts: S3Options) {
    this.keys = { accessKey: opts.accessKey, secretKey: opts.secretKey, region: opts.region };
    this.fetch = opts.fetch ?? fetch;
  }

  /** The object URL for a key. */
  url(key: string): URL {
    const base = new URL(this.opts.endpoint);
    const prefix = base.pathname.replace(/\/+$/, "");
    const path = encodePath(checkKey(key));
    if (this.opts.forcePathStyle) {
      base.pathname = `${prefix}/${encodePath(this.opts.bucket)}/${path}`;
    } else {
      base.hostname = `${this.opts.bucket}.${base.hostname}`;
      base.pathname = `${prefix}/${path}`;
    }
    return base;
  }

  private async request(
    method: string,
    key: string,
    body?: Uint8Array,
    headers?: Record<string, string>,
  ): Promise<Response> {
    const url = this.url(key);
    const signed = signRequest({
      keys: this.keys,
      method,
      url,
      payloadHash: sha256Hex(body ?? new Uint8Array()),
      ...(headers ? { headers } : {}),
    });
    const { host: _host, ...send } = signed;
    let res: Response;
    try {
      res = await this.fetch(url, {
        method,
        headers: send,
        ...(body ? { body: Buffer.from(body) } : {}),
        signal: AbortSignal.timeout(this.opts.timeoutMs ?? 60_000),
      });
    } catch (error) {
      throw new NetworkError(`object storage ${method} failed`, null, { cause: error });
    }
    if (res.status === 404) {
      await res.body?.cancel();
      throw new NotFoundError(`object ${key} not found`);
    }
    if (!res.ok) {
      const text = (await res.text().catch(() => "")).slice(0, 500);
      const code = /<Code>([^<]+)<\/Code>/.exec(text)?.[1] ?? `HTTP ${res.status}`;
      throw new NetworkError(`object storage ${method} failed: ${code}`, { status: res.status });
    }
    return res;
  }

  async put(key: string, bytes: Uint8Array, mimeType: string): Promise<void> {
    const res = await this.request("PUT", key, bytes, { "content-type": mimeType });
    await res.body?.cancel();
  }

  async get(key: string): Promise<Uint8Array> {
    const res = await this.request("GET", key);
    return new Uint8Array(await res.arrayBuffer());
  }

  async open(key: string): Promise<StoredObject> {
    const res = await this.request("GET", key);
    if (!res.body) throw new NotFoundError(`object ${key} not found`);
    return { body: res.body, size: Number(res.headers.get("content-length") ?? -1) };
  }

  presign(key: string, opts: PresignOptions): string {
    const url = this.url(key);
    if (opts.contentDisposition)
      url.searchParams.set("response-content-disposition", opts.contentDisposition);
    if (opts.contentType) url.searchParams.set("response-content-type", opts.contentType);
    return presignUrl({
      keys: this.keys,
      method: "GET",
      url,
      expiresSeconds: Math.min(Math.max(1, opts.expiresSeconds), 7 * 24 * 3600),
    }).toString();
  }

  async delete(key: string): Promise<void> {
    try {
      const res = await this.request("DELETE", key);
      await res.body?.cancel();
    } catch (error) {
      if (!(error instanceof NotFoundError)) throw error;
    }
  }
}

export interface StorageEnv {
  S3_ENDPOINT?: string | undefined;
  S3_BUCKET?: string | undefined;
  S3_ACCESS_KEY?: string | undefined;
  S3_SECRET_KEY?: string | undefined;
  S3_REGION?: string | undefined;
  S3_FORCE_PATH_STYLE?: boolean | undefined;
}

/**
 * The instance's artifact storage: new objects go to `primary`; `forKind` reads an existing row
 * from the store that wrote it (`artifacts.storage`), so local artifacts written before S3 was
 * configured stay readable.
 */
export interface ArtifactStorage {
  readonly primary: ArtifactStore;
  /** The store for an `artifacts.storage` value; throws NotFoundError when it is not configured. */
  forKind(kind: string): ArtifactStore;
}

export function artifactStorage(
  primary: ArtifactStore,
  ...others: ArtifactStore[]
): ArtifactStorage {
  const all = [primary, ...others];
  return {
    primary,
    forKind: (kind) => {
      const store = all.find((s) => s.kind === kind);
      if (!store) throw new NotFoundError(`artifact storage "${kind}" is not configured`);
      return store;
    },
  };
}

/** S3 when all four S3 variables are set (local stays readable), otherwise the local directory. */
export function artifactStorageFrom(env: StorageEnv, localRoot: string): ArtifactStorage {
  const local = new LocalArtifactStore(localRoot);
  if (env.S3_ENDPOINT && env.S3_BUCKET && env.S3_ACCESS_KEY && env.S3_SECRET_KEY)
    return artifactStorage(
      new S3ArtifactStore({
        endpoint: env.S3_ENDPOINT,
        bucket: env.S3_BUCKET,
        accessKey: env.S3_ACCESS_KEY,
        secretKey: env.S3_SECRET_KEY,
        region: env.S3_REGION ?? "us-east-1",
        forcePathStyle: env.S3_FORCE_PATH_STYLE ?? true,
      }),
      local,
    );
  return artifactStorage(local);
}
