/**
 * `@flowaid/nodes-langchain/manifest`: the node manifests, provider descriptors and the template
 * as data, without loading LangChain or any executor — for the API and docs. Generated by
 * `scripts/build-manifest.ts`.
 */
import type { NodeManifest } from "@flowaid/workflow-core";
import file from "../manifest.json" with { type: "json" };
import knowledgeAssistant from "../templates/knowledge-assistant-langchain-rag.json" with { type: "json" };
import knowledgeAssistantResources from "../templates/knowledge-assistant-langchain-rag.resources.json" with { type: "json" };

export const langchainManifests: readonly NodeManifest[] = (
  file as unknown as { nodes: NodeManifest[] }
).nodes;
export const langchainProviderDescriptors: readonly {
  id: string;
  kind: string;
  credentialType: string | null;
}[] = file.providers;
export const langchainManifestPackage = { name: file.package, version: file.version };

export interface LangChainTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  requires: string[];
  definition: unknown;
  requiredResources: unknown[];
}

export const langchainTemplates: readonly LangChainTemplate[] = [
  {
    ...knowledgeAssistantResources,
    definition: knowledgeAssistant,
  },
].map(({ id, name, description, category, requires, requiredResources, definition }) => ({
  id,
  name,
  description,
  category,
  requires,
  requiredResources,
  definition,
}));
