/**
 * Support reply with safety gate — generated by FlowAId from the workflow definition.
 * Edit freely: `pnpm validate` compiles it and reports what changed against workflow.plan.json.
 */
import {
  branch,
  defineWorkflow,
  edge,
  human,
  input,
  lit,
  obj,
  output,
  ref,
  secret,
  task,
  tpl,
  variable,
} from "@flowaid/workflow-sdk";

export const workflow = defineWorkflow({
  id: "5b1c2b60-6e0f-4a1a-9b0e-1b1a2c3d4e5f",
  name: "Support reply with safety gate",
  description:
    "Classify a support message, fetch account context for billing, draft a reply, verify it is safe, gate on confidence.",
  inputs: {
    type: "object",
    properties: {
      message: { type: "string", "x-dataClass": "pii" },
      customer_id: { type: "string" },
      tier: { type: "string", enum: ["free", "gold"] },
    },
    required: ["message", "customer_id"],
    additionalProperties: false,
  },
  outputs: {
    type: "object",
    properties: {
      reply: { type: "string" },
      team: { type: "string" },
      auto_sent: { type: "boolean" },
      approved_by: { type: ["string", "null"] },
    },
    required: ["reply", "team", "auto_sent"],
  },
  variables: [
    variable(
      "crmBaseUrl",
      { type: "string" },
      { default: "https://crm.example.com", source: "environment" },
    ),
    variable("autoSendThreshold", { type: "number", minimum: 0, maximum: 1 }, { default: 0.85 }),
  ],
  secrets: [
    secret("TYPESAFE_API_KEY", "typesafe.api_key"),
    secret("OPENAI_API_KEY", "openai.api_key"),
    secret("CRM_TOKEN", "http.bearer", { required: false }),
  ],
  execution: {
    timeoutMs: 180000,
    maxCostUsd: 0.5,
    maxNodeRuns: 2000,
    maxSubflowDepth: 4,
    concurrency: 8,
    defaultRetry: {
      maxAttempts: 1,
      backoff: { type: "exponential", initialMs: 500, maxMs: 30000, factor: 2, jitter: true },
      allowOnIrreversible: false,
    },
    defaultNodeTimeoutMs: 120000,
    decisions: {
      primary: { provider: "typesafe", model: "jev-latest" },
      failover: [],
      batching: true,
    },
    privacy: { sensitive: false, containsPII: false, doNotPersist: false, redactFields: [] },
    retention: "standard",
  },
  nodes: {
    start: input("Ticket"),
    intent: task("flowaid.decision.choice", {
      typeVersion: "1.0.0",
      name: "Intent",
      config: {
        instructions: "Which team should handle this support request?",
        options: {
          billing: "Invoices, charges, refunds",
          technical: "Bugs, outages, integrations",
          security: "Fraud, stolen cards, account takeover",
          general: "Anything else",
        },
      },
      inputs: {
        state: obj({
          message: ref("start", "message"),
          tier: ref("start", "tier").default("free"),
        }),
      },
      credentials: { typesafe: "TYPESAFE_API_KEY" },
    }),
    route: branch("Billing?", {
      cases: [{ port: "billing", when: "intent.decision.value == 'billing'" }],
      defaultPort: "other",
    }),
    fetch_account: task("flowaid.tools.http", {
      typeVersion: "1.0.0",
      name: "Fetch account",
      config: {
        method: "GET",
        url: "{{ $vars.crmBaseUrl }}/customers/{{ start.customer_id }}",
        responseType: "json",
        timeoutMs: 5000,
      },
      credentials: { auth: "CRM_TOKEN" },
      policy: {
        retry: {
          maxAttempts: 3,
          backoff: { type: "exponential", initialMs: 500, maxMs: 30000, factor: 2, jitter: true },
          allowOnIrreversible: false,
        },
        onError: "ignore",
      },
    }),
    draft: task("flowaid.ai.generate", {
      typeVersion: "1.0.0",
      name: "Draft reply",
      config: {
        model: { provider: "openai", model: "gpt-4.1-mini" },
        temperature: 0.3,
        maxOutputTokens: 600,
        stream: true,
        system: "You are a concise, friendly support agent. Never promise refunds or credits.",
      },
      inputs: {
        prompt: tpl(
          "Team: {{ intent.decision.value }} (confidence {{ round(intent.decision.confidence, 2) }})\nAccount: {{ coalesce(fetch_account.body, {}) | json }}\n\nCustomer message:\n{{ start.message }}\n\nWrite the reply.",
        ),
      },
      credentials: { llm: "OPENAI_API_KEY" },
    }),
    safe: task("flowaid.decision.boolean", {
      typeVersion: "1.0.0",
      name: "Safe to send?",
      config: {
        instructions: "Is this reply safe to send without human review?",
        criteria: {
          true: "Polite, accurate, makes no financial or legal commitment",
          false: "Speculates, promises refunds, discloses internal data, or is rude",
        },
      },
      inputs: {
        state: obj({
          reply: ref("draft", "text"),
          message: ref("start", "message"),
          team: ref("intent", "decision", "/value"),
        }),
      },
      credentials: { typesafe: "TYPESAFE_API_KEY" },
    }),
    gate: task("flowaid.decision.confidence_gate", {
      typeVersion: "1.0.0",
      name: "Confidence gate",
      config: {
        threshold: { kind: "ref", ref: { kind: "var", name: "autoSendThreshold" } },
        requireValue: true,
      },
      inputs: { decision: ref("safe", "decision") },
    }),
    approve: human("Approve reply", {
      mode: {
        type: "review",
        value: ref("draft", "text"),
        schema: { type: "string", minLength: 1 },
      },
      title: tpl("Review reply for {{ start.customer_id }} ({{ intent.decision.value }})"),
      context: { message: ref("start", "message"), safety: ref("safe", "decision") },
      assignees: ["role:support_lead"],
      expiresInMs: 86400000,
      onExpire: "route",
      externalReview: true,
    }),
    out_auto: output("Auto reply", {
      value: obj({
        reply: ref("draft", "text"),
        team: ref("intent", "decision", "/value"),
        auto_sent: lit(true),
        approved_by: lit(null),
      }),
      outcome: "auto",
    }),
    out_human: output("Reviewed reply", {
      value: obj({
        reply: ref("approve", "value"),
        team: ref("intent", "decision", "/value"),
        auto_sent: lit(false),
        approved_by: ref("approve", "decision", "/by"),
      }),
      outcome: "human_approved",
    }),
    out_rejected: output("Rejected", {
      value: obj({
        reply: lit(""),
        team: ref("intent", "decision", "/value"),
        auto_sent: lit(false),
        approved_by: lit(null),
      }),
      outcome: "rejected",
    }),
  },
  edges: [
    edge({ node: "route", port: "billing" }, "fetch_account", "c1"),
    edge({ node: "gate", port: "pass" }, "out_auto", "c2"),
    edge({ node: "gate", port: "review" }, "approve", "c3"),
    edge({ node: "approve", port: "approved" }, "out_human", "c4"),
    edge({ node: "approve", port: "rejected" }, "out_rejected", "c5"),
    edge({ node: "approve", port: "expired" }, "out_rejected", "c6"),
  ],
  layout: {
    nodes: {
      start: { x: 0, y: 220 },
      intent: { x: 260, y: 220 },
      route: { x: 520, y: 220 },
      fetch_account: { x: 780, y: 80 },
      draft: { x: 1040, y: 220 },
      safe: { x: 1300, y: 220 },
      gate: { x: 1560, y: 220 },
      approve: { x: 1820, y: 360 },
      out_auto: { x: 1820, y: 80 },
      out_human: { x: 2080, y: 300 },
      out_rejected: { x: 2080, y: 480 },
    },
  },
});

export default workflow;
