/**
 * Research Agent — generated by FlowAId from the workflow definition.
 * Edit freely: `pnpm validate` compiles it and reports what changed against workflow.plan.json.
 */
import {
  defineWorkflow,
  edge,
  expr,
  foreach,
  input,
  lit,
  loop,
  obj,
  output,
  ref,
  secret,
  task,
  tpl,
} from "@flowaid/workflow-sdk";

export const workflow = defineWorkflow({
  id: "b4d6f8a0-2c4e-4a6b-8d0f-1e3a5c7b9d2f",
  name: "Research Agent",
  description:
    "Bounded research loop: plan searches, run them in parallel, judge each result, accumulate scored evidence in the loop carry, synthesise and decide whether the answer is complete.",
  inputs: {
    type: "object",
    properties: {
      question: { type: "string" },
      max_rounds: { type: "integer", minimum: 1, maximum: 5, default: 3 },
    },
    required: ["question"],
  },
  outputs: {
    type: "object",
    properties: {
      answer: { type: "string" },
      evidence: { type: "array", items: { type: "object" } },
      complete: { type: "boolean" },
      rounds: { type: "integer" },
    },
    required: ["answer", "evidence", "complete"],
  },
  secrets: [
    secret("TYPESAFE_API_KEY", "typesafe.api_key"),
    secret("ANTHROPIC_API_KEY", "anthropic.api_key"),
    secret("SEARCH_API", "http.api_key"),
  ],
  execution: {
    timeoutMs: 600000,
    maxCostUsd: 2,
    maxTokens: 400000,
    maxNodeRuns: 2000,
    maxSubflowDepth: 4,
    concurrency: 6,
    defaultRetry: {
      maxAttempts: 1,
      backoff: { type: "exponential", initialMs: 500, maxMs: 30000, factor: 2, jitter: true },
      allowOnIrreversible: false,
    },
    defaultNodeTimeoutMs: 120000,
    decisions: {
      primary: { provider: "typesafe", model: "jev-latest" },
      failover: [],
      batching: true,
    },
    privacy: { sensitive: false, containsPII: false, doNotPersist: false, redactFields: [] },
    retention: "standard",
  },
  nodes: {
    start: input("Question"),
    research: loop("Research rounds", {
      carrySchema: {
        type: "object",
        properties: {
          evidence: { type: "array", items: { type: "object" } },
          gap: { type: "string" },
        },
        required: ["evidence", "gap"],
      },
      carry: {
        initial: { evidence: [], gap: "none" },
        next: {
          evidence: ref("store", "result"),
          gap: ref("completeness", "answers", "/gap/value"),
        },
      },
      result: {
        answer: ref("synthesis", "structured", "/answer"),
        complete: ref("completeness", "answers", "/complete/value"),
      },
      exitWhen:
        "completeness.answers.complete.value && completeness.answers.complete.confidence >= 0.8 || $scope.iteration + 1 >= start.max_rounds",
      bounds: { maxIterations: 5, timeoutMs: 480000, maxCostUsd: 1.5 },
    }),
    planner: task("flowaid.ai.structured_generate", {
      typeVersion: "1.0.0",
      name: "Plan queries",
      config: {
        model: { provider: "anthropic", model: "claude-sonnet-4-5" },
        schema: {
          type: "object",
          required: ["queries"],
          properties: {
            queries: {
              type: "array",
              minItems: 1,
              maxItems: 4,
              items: {
                type: "object",
                required: ["query", "source"],
                properties: {
                  query: { type: "string" },
                  source: { type: "string", enum: ["web", "papers"] },
                },
              },
            },
          },
        },
      },
      inputs: {
        prompt: tpl(
          "Question: {{ start.question }}\nRound {{ $scope.iteration + 1 }}. Known gap: {{ $scope.carry.gap }}\nEvidence so far: {{ $scope.carry.evidence | json }}\nPropose up to 4 targeted searches.",
        ),
      },
      credentials: { llm: "ANTHROPIC_API_KEY" },
      parent: "research",
    }),
    search_all: foreach("Run searches", {
      items: ref("planner", "structured", "/queries"),
      failurePolicy: "collect",
      bounds: { maxIterations: 4 },
      collect: obj({
        query: ref.scope("item", "/query"),
        result: expr("first(web.body.results)"),
        judgment: ref("judge", "answers"),
      }),
      parent: "research",
    }),
    web: task("flowaid.tools.http", {
      typeVersion: "1.0.0",
      name: "Search",
      config: {
        method: "GET",
        url: "https://search.example.com/v1?q={{ $scope.item.query }}&source={{ $scope.item.source }}",
        responseType: "json",
      },
      credentials: { auth: "SEARCH_API" },
      parent: "search_all",
      policy: {
        retry: {
          maxAttempts: 2,
          backoff: { type: "exponential", initialMs: 500, maxMs: 30000, factor: 2, jitter: true },
          allowOnIrreversible: false,
        },
        onError: "fail",
      },
    }),
    judge: task("flowaid.decision.batch", {
      typeVersion: "1.0.0",
      name: "Judge result",
      config: {
        questions: {
          relevant: {
            kind: "score",
            instructions: "How relevant is this result to the question?",
            levels: ["Irrelevant", "Weak", "Partial", "Strong", "Direct answer"],
          },
          reliable: {
            kind: "score",
            instructions: "How reliable is the source?",
            levels: ["Unreliable", "Questionable", "Mixed", "Reliable", "Authoritative"],
          },
        },
      },
      inputs: {
        state: obj({ question: ref("start", "question"), result: expr("first(web.body.results)") }),
      },
      credentials: { typesafe: "TYPESAFE_API_KEY" },
      parent: "search_all",
    }),
    store: task("flowaid.data.transform", {
      typeVersion: "1.0.0",
      name: "Accumulate evidence",
      config: {
        output: { type: "array", items: { type: "object" } },
        expr: "concat($scope.carry.evidence, filter(search_all.results, r => r.judgment.relevant.value >= 2 && r.judgment.reliable.value >= 2))",
      },
      parent: "research",
    }),
    synthesis: task("flowaid.ai.structured_generate", {
      typeVersion: "1.0.0",
      name: "Synthesize",
      config: {
        model: { provider: "anthropic", model: "claude-sonnet-4-5" },
        schema: {
          type: "object",
          required: ["answer", "citations"],
          properties: {
            answer: { type: "string" },
            citations: { type: "array", items: { type: "string" } },
          },
        },
      },
      inputs: {
        prompt: tpl(
          "Question: {{ start.question }}\nEvidence (scored): {{ store.result | json }}\nWrite a sourced answer; cite by url.",
        ),
      },
      credentials: { llm: "ANTHROPIC_API_KEY" },
      parent: "research",
    }),
    completeness: task("flowaid.decision.batch", {
      typeVersion: "1.0.0",
      name: "Complete?",
      config: {
        questions: {
          complete: {
            kind: "boolean",
            instructions: "Does the answer fully address the question with adequate evidence?",
            criteria: {
              true: "Complete and well-supported",
              false: "Missing aspects or weak evidence",
            },
          },
          gap: {
            kind: "choice",
            instructions: "What is the main gap, if any?",
            options: {
              none: "No gap",
              missing_data: "Key facts missing",
              conflicting: "Sources conflict",
              outdated: "Evidence may be stale",
            },
          },
        },
      },
      inputs: {
        state: obj({
          question: ref("start", "question"),
          answer: ref("synthesis", "structured", "/answer"),
          evidence_count: expr("len(store.result)"),
        }),
      },
      credentials: { typesafe: "TYPESAFE_API_KEY" },
      parent: "research",
    }),
    out_done: output("Answer", {
      value: obj({
        answer: ref("research", "result", "/answer"),
        evidence: ref("research", "carry", "/evidence"),
        complete: ref("research", "result", "/complete"),
        rounds: ref("research", "iterations"),
      }),
      outcome: "complete",
    }),
    out_partial: output("Best effort", {
      value: obj({
        answer: expr("coalesce(research.result.answer, '')"),
        evidence: ref("research", "carry", "/evidence"),
        complete: lit(false),
        rounds: ref("research", "iterations"),
      }),
      outcome: "partial",
    }),
  },
  edges: [
    edge({ node: "research", port: "done" }, "out_done", "c1"),
    edge({ node: "research", port: "exhausted" }, "out_partial", "c2"),
  ],
  layout: {
    nodes: {
      start: { x: 0, y: 220 },
      research: { x: 260, y: 220 },
      planner: { x: 300, y: 360 },
      search_all: { x: 540, y: 360 },
      web: { x: 580, y: 500 },
      judge: { x: 820, y: 500 },
      store: { x: 780, y: 360 },
      synthesis: { x: 1020, y: 360 },
      completeness: { x: 1260, y: 360 },
      out_done: { x: 520, y: 220 },
      out_partial: { x: 780, y: 220 },
    },
  },
});

export default workflow;
