/**
 * Intelligent Support Triage — generated by FlowAId from the workflow definition.
 * Edit freely: `pnpm validate` compiles it and reports what changed against workflow.plan.json.
 */
import {
  branch,
  defineWorkflow,
  edge,
  human,
  input,
  join,
  lit,
  obj,
  output,
  ref,
  secret,
  task,
  tpl,
  variable,
} from "@flowaid/workflow-sdk";

export const workflow = defineWorkflow({
  id: "9c2e5f7a-3b1d-4e8f-a6c4-2d7b9e1f3a5c",
  name: "Intelligent Support Triage",
  description:
    "Batch-judge a support ticket (team, urgency, escalation), gather team-specific context, draft a reply, run safety checks and gate on confidence with a human fallback.",
  inputs: {
    type: "object",
    properties: {
      message: { type: "string", "x-dataClass": "pii" },
      customer_id: { type: "string" },
      channel: { type: "string", enum: ["email", "chat", "api"] },
    },
    required: ["message", "customer_id"],
  },
  outputs: {
    type: "object",
    properties: {
      team: { type: "string" },
      urgency: { type: "number" },
      reply: { type: "string" },
      disposition: { type: "string", enum: ["auto", "human_approved", "escalated"] },
    },
    required: ["team", "urgency", "reply", "disposition"],
  },
  variables: [
    variable("billingBase", { type: "string" }, { source: "environment" }),
    variable("autoThreshold", { type: "number" }, { default: 0.9 }),
  ],
  secrets: [
    secret("TYPESAFE_API_KEY", "typesafe.api_key"),
    secret("OPENAI_API_KEY", "openai.api_key"),
    secret("BILLING_API", "http.bearer"),
    secret("STATUS_API", "http.bearer", { required: false }),
  ],
  execution: {
    timeoutMs: 180000,
    maxCostUsd: 0.25,
    maxNodeRuns: 2000,
    maxSubflowDepth: 4,
    concurrency: 8,
    defaultRetry: {
      maxAttempts: 1,
      backoff: { type: "exponential", initialMs: 500, maxMs: 30000, factor: 2, jitter: true },
      allowOnIrreversible: false,
    },
    defaultNodeTimeoutMs: 120000,
    decisions: {
      primary: { provider: "typesafe", model: "jev-latest" },
      failover: [{ provider: "llm", model: { provider: "openai", model: "gpt-4.1-mini" } }],
      batching: true,
    },
    privacy: { sensitive: false, containsPII: false, doNotPersist: false, redactFields: [] },
    retention: "standard",
  },
  nodes: {
    start: input("Ticket"),
    judgments: task("flowaid.decision.batch", {
      typeVersion: "1.0.0",
      name: "Triage judgments",
      config: {
        questions: {
          intent: {
            kind: "choice",
            instructions: "Which team should handle this?",
            options: {
              billing: "Invoices, charges, refunds, subscriptions",
              technical: "Bugs, errors, outages, integrations",
              security: "Fraud, stolen cards, account takeover, data exposure",
              general: "Anything else",
            },
          },
          urgency: {
            kind: "score",
            instructions: "How urgent is this request?",
            levels: ["Not urgent", "Low", "Moderate", "High", "Critical"],
          },
          escalate: {
            kind: "boolean",
            instructions:
              "Should a human handle this from the start (legal threat, churn risk, abuse)?",
            criteria: { true: "Human must handle", false: "Automation may proceed" },
          },
        },
      },
      inputs: {
        state: obj({
          message: ref("start", "message"),
          channel: ref("start", "channel").default("api"),
        }),
      },
      credentials: { typesafe: "TYPESAFE_API_KEY", llm: "OPENAI_API_KEY" },
    }),
    esc_gate: branch("Escalate now?", {
      cases: [
        {
          port: "escalate",
          when: "judgments.answers.escalate.value || judgments.answers.urgency.value >= 3.5",
        },
      ],
      defaultPort: "continue",
    }),
    route: branch("Route by team", {
      cases: [
        { port: "billing", when: "judgments.answers.intent.value == 'billing'" },
        { port: "technical", when: "judgments.answers.intent.value == 'technical'" },
        { port: "security", when: "judgments.answers.intent.value == 'security'" },
      ],
      defaultPort: "general",
    }),
    billing_lookup: task("flowaid.tools.http", {
      typeVersion: "1.0.0",
      name: "Billing lookup",
      config: {
        method: "GET",
        url: "{{ $vars.billingBase }}/customers/{{ start.customer_id }}/invoices?limit=3",
        responseType: "json",
      },
      credentials: { auth: "BILLING_API" },
      policy: {
        retry: {
          maxAttempts: 3,
          backoff: { type: "exponential", initialMs: 500, maxMs: 30000, factor: 2, jitter: true },
          allowOnIrreversible: false,
        },
        onError: "ignore",
      },
    }),
    status_lookup: task("flowaid.tools.http", {
      typeVersion: "1.0.0",
      name: "Status page",
      config: {
        method: "GET",
        url: "https://status.example.com/api/v2/incidents/unresolved.json",
        responseType: "json",
      },
      credentials: { auth: "STATUS_API" },
      policy: { onError: "ignore" },
    }),
    security_kb: task("flowaid.tools.mcp", {
      typeVersion: "1.0.0",
      name: "Security playbook",
      config: { serverId: "00000000-0000-4000-8000-736563757269", tool: "search_playbooks" },
      inputs: { query: ref("start", "message") },
    }),
    context: join("Context", {
      inputs: {
        billing: ref("billing_lookup", "body"),
        status: ref("status_lookup", "body"),
        security: ref("security_kb", "result"),
      },
    }),
    draft: task("flowaid.ai.generate", {
      typeVersion: "1.0.0",
      name: "Draft response",
      config: {
        model: { provider: "openai", model: "gpt-4.1-mini" },
        temperature: 0.2,
        maxOutputTokens: 500,
        stream: true,
        system: "You write concise, accurate support replies. Never promise refunds or timelines.",
      },
      inputs: {
        prompt: tpl(
          "Team: {{ judgments.answers.intent.value }} (p={{ round(judgments.answers.intent.confidence, 2) }})\nUrgency: {{ judgments.answers.urgency.levelLabel }}\nContext: {{ context.values | json }}\n\nCustomer message:\n{{ start.message }}",
        ),
      },
      credentials: { llm: "OPENAI_API_KEY" },
    }),
    safety: task("flowaid.decision.batch", {
      typeVersion: "1.0.0",
      name: "Safety checks",
      config: {
        questions: {
          safe: {
            kind: "boolean",
            instructions:
              "Is the reply safe to send (no promises, no policy violations, no PII leakage)?",
            criteria: { true: "Safe", false: "Unsafe" },
          },
          on_topic: {
            kind: "boolean",
            instructions: "Does the reply address the customer's actual issue?",
          },
        },
      },
      inputs: { state: obj({ message: ref("start", "message"), reply: ref("draft", "text") }) },
      credentials: { typesafe: "TYPESAFE_API_KEY", llm: "OPENAI_API_KEY" },
    }),
    gate: task("flowaid.decision.confidence_gate", {
      typeVersion: "1.0.0",
      name: "Confidence gate",
      config: {
        threshold: { kind: "ref", ref: { kind: "var", name: "autoThreshold" } },
        requireValue: true,
      },
      inputs: { decision: ref("safety", "answers", "/safe") },
    }),
    approve: human("Agent approval", {
      mode: { type: "review", value: ref("draft", "text"), schema: { type: "string" } },
      title: tpl(
        "Review reply for a {{ judgments.answers.intent.value }} ticket (safety p={{ round(safety.answers.safe.pYes, 2) }})",
      ),
      context: { message: ref("start", "message"), safety: ref("safety", "answers") },
      assignees: ["role:support_lead"],
      expiresInMs: 7200000,
      onExpire: "route",
      escalation: { afterMs: 1800000, to: ["role:admin"] },
      externalReview: true,
    }),
    out_auto: output("Auto respond", {
      value: obj({
        team: ref("judgments", "answers", "/intent/value"),
        urgency: ref("judgments", "answers", "/urgency/value"),
        reply: ref("draft", "text"),
        disposition: lit("auto"),
      }),
      outcome: "auto",
    }),
    out_human: output("Human approved", {
      value: obj({
        team: ref("judgments", "answers", "/intent/value"),
        urgency: ref("judgments", "answers", "/urgency/value"),
        reply: ref("approve", "value"),
        disposition: lit("human_approved"),
      }),
      outcome: "human_approved",
    }),
    out_esc: output("Escalated", {
      value: obj({
        team: ref("judgments", "answers", "/intent/value"),
        urgency: ref("judgments", "answers", "/urgency/value"),
        reply: lit(""),
        disposition: lit("escalated"),
      }),
      outcome: "escalated",
    }),
  },
  edges: [
    edge({ node: "esc_gate", port: "escalate" }, "out_esc", "c1"),
    edge({ node: "esc_gate", port: "continue" }, "route", "c2"),
    edge({ node: "route", port: "billing" }, "billing_lookup", "c3"),
    edge({ node: "route", port: "technical" }, "status_lookup", "c4"),
    edge({ node: "route", port: "security" }, "security_kb", "c5"),
    edge({ node: "billing_lookup", port: "done" }, "context", "c6"),
    edge({ node: "status_lookup", port: "done" }, "context", "c7"),
    edge({ node: "security_kb", port: "done" }, "context", "c8"),
    edge({ node: "route", port: "general" }, "context", "c9"),
    edge({ node: "context", port: "done" }, "draft", "c9b"),
    edge({ node: "gate", port: "pass" }, "out_auto", "c10"),
    edge({ node: "gate", port: "review" }, "approve", "c11"),
    edge({ node: "gate", port: "fail" }, "approve", "c12"),
    edge({ node: "approve", port: "approved" }, "out_human", "c13"),
    edge({ node: "approve", port: "rejected" }, "out_esc", "c14"),
    edge({ node: "approve", port: "expired" }, "out_esc", "c15"),
  ],
  layout: {
    nodes: {
      start: { x: 0, y: 220 },
      judgments: { x: 260, y: 220 },
      esc_gate: { x: 520, y: 220 },
      route: { x: 780, y: 220 },
      billing_lookup: { x: 1040, y: 220 },
      status_lookup: { x: 1300, y: 220 },
      security_kb: { x: 1560, y: 220 },
      context: { x: 1820, y: 220 },
      draft: { x: 2080, y: 220 },
      safety: { x: 2340, y: 220 },
      gate: { x: 2600, y: 220 },
      approve: { x: 2860, y: 220 },
      out_auto: { x: 3120, y: 220 },
      out_human: { x: 3380, y: 220 },
      out_esc: { x: 3640, y: 220 },
    },
  },
});

export default workflow;
