/**
 * Document agent (PageIndex) — generated by FlowAId from the workflow definition.
 * Edit freely: `pnpm validate` compiles it and reports what changed against workflow.plan.json.
 */
import { defineWorkflow, input, obj, output, ref, secret, task } from "@flowaid/workflow-sdk";

export const workflow = defineWorkflow({
  id: "7fe5108f-300a-478d-8a3f-7f2bd8d458fd",
  name: "Document agent (PageIndex)",
  description:
    "A bounded agent that reads indexed documents with read-only tools (outline, pages, section search) confined to one knowledge source, and cites the document and page for what it states.",
  inputs: {
    type: "object",
    properties: { task: { type: "string", minLength: 1, maxLength: 20000 } },
    required: ["task"],
  },
  outputs: {
    type: "object",
    properties: {
      answer: { type: "string" },
      steps: { type: "integer" },
      tool_calls: { type: "array", items: { type: "object" } },
    },
    required: ["answer"],
  },
  secrets: [
    secret("TYPESAFE_API_KEY", "typesafe.api_key"),
    secret("OPENAI_API_KEY", "openai.api_key"),
  ],
  execution: {
    timeoutMs: 600000,
    maxCostUsd: 0.75,
    maxNodeRuns: 2000,
    maxSubflowDepth: 4,
    concurrency: 8,
    defaultRetry: {
      maxAttempts: 1,
      backoff: { type: "exponential", initialMs: 500, maxMs: 30000, factor: 2, jitter: true },
      allowOnIrreversible: false,
    },
    defaultNodeTimeoutMs: 120000,
    decisions: {
      primary: { provider: "typesafe", model: "jev-latest" },
      failover: [],
      batching: true,
    },
    privacy: { sensitive: false, containsPII: false, doNotPersist: false, redactFields: [] },
    retention: "standard",
  },
  nodes: {
    start: input("Task"),
    agent: task("flowaid.ai.agent", {
      typeVersion: "1.0.0",
      name: "Document agent",
      config: {
        model: { provider: "openai", model: "gpt-4.1-mini" },
        system:
          "You answer questions about the documents you can read. Look at the outline first, then read or search the relevant pages. Base every factual statement on page text you read and cite it as (document name, p. N). If the documents do not answer the question, say so and say what is missing.",
        temperature: 0.1,
        maxSteps: 8,
        maxToolCalls: 16,
        maxCostUsd: 0.5,
        documents: { sourceIds: ["00000000-0000-4000-8000-646f63756d65"] },
      },
      inputs: { task: ref("start", "task") },
      credentials: { llm: "OPENAI_API_KEY", typesafe: "TYPESAFE_API_KEY" },
    }),
    out: output("Answer", {
      value: obj({
        answer: ref("agent", "answer"),
        steps: ref("agent", "steps"),
        tool_calls: ref("agent", "tool_calls"),
      }),
    }),
  },
  layout: {
    nodes: { start: { x: 0, y: 200 }, agent: { x: 260, y: 200 }, out: { x: 520, y: 200 } },
  },
});

export default workflow;
