/**
 * GitHub Issue Triage (knowledge base) — generated by FlowAId from the workflow definition.
 * Edit freely: `pnpm validate` compiles it and reports what changed against workflow.plan.json.
 */
import {
  arr,
  branch,
  defineWorkflow,
  edge,
  expr,
  input,
  lit,
  obj,
  output,
  ref,
  secret,
  task,
  tpl,
  trigger,
} from "@flowaid/workflow-sdk";

export const workflow = defineWorkflow({
  id: "8c2f4a61-3b7d-4e9a-b5c0-2d1e6f7a8b93",
  name: "GitHub Issue Triage (knowledge base)",
  description:
    "Webhook-triggered triage of new GitHub issues with duplicate detection over a knowledge base of past issues: hybrid search (meaning and keywords) finds similar issues, TypeSafe judges whether the top candidate is a duplicate, labels go on through the GitHub MCP server, and every new issue is indexed so later ones can find it.",
  inputs: {
    type: "object",
    properties: {
      action: { type: "string" },
      issue: {
        type: "object",
        properties: {
          number: { type: "integer" },
          title: { type: "string" },
          body: { type: ["string", "null"] },
          html_url: { type: "string" },
        },
        required: ["number", "title", "html_url"],
      },
      repository: {
        type: "object",
        properties: { full_name: { type: "string" } },
        required: ["full_name"],
      },
    },
    required: ["action", "issue", "repository"],
  },
  outputs: {
    type: "object",
    properties: {
      handled: { type: "boolean" },
      labels: { type: "array", items: { type: "string" } },
      duplicate_of: { type: ["integer", "null"] },
      route: { type: "string" },
    },
    required: ["handled"],
  },
  secrets: [secret("TYPESAFE_API_KEY", "typesafe.api_key"), secret("GITHUB_MCP", "mcp.headers")],
  triggers: [
    trigger.webhook({
      path: "github-issues",
      signature: "hmac_sha256",
      responseMode: "async",
      inputPointer: "/body",
      allowedHeaders: ["x-github-event", "x-github-delivery"],
    }),
  ],
  execution: {
    timeoutMs: 120000,
    maxCostUsd: 0.2,
    maxNodeRuns: 2000,
    maxSubflowDepth: 4,
    concurrency: 8,
    defaultRetry: {
      maxAttempts: 1,
      backoff: { type: "exponential", initialMs: 500, maxMs: 30000, factor: 2, jitter: true },
      allowOnIrreversible: false,
    },
    defaultNodeTimeoutMs: 120000,
    decisions: {
      primary: { provider: "typesafe", model: "jev-latest" },
      failover: [],
      batching: true,
    },
    privacy: { sensitive: false, containsPII: false, doNotPersist: false, redactFields: [] },
    retention: "standard",
  },
  nodes: {
    start: input("Webhook"),
    opened: branch("Opened?", {
      cases: [{ port: "yes", when: "start.action == 'opened' || start.action == 'reopened'" }],
      defaultPort: "no",
    }),
    actionable: task("flowaid.decision.boolean", {
      typeVersion: "1.0.0",
      name: "Actionable?",
      config: {
        instructions:
          "Is this issue actionable by maintainers (a real bug, feature, docs or usage question rather than spam/empty)?",
        criteria: { true: "Actionable", false: "Spam, empty or off-topic" },
      },
      inputs: {
        state: obj({
          title: ref("start", "issue").default({}),
          body: expr("coalesce(start.issue.body, '')"),
        }),
      },
      credentials: { typesafe: "TYPESAFE_API_KEY" },
    }),
    act_gate: branch("Actionable gate", {
      cases: [
        { port: "yes", when: "actionable.decision.value && actionable.decision.confidence >= 0.7" },
      ],
      defaultPort: "no",
    }),
    classify: task("flowaid.decision.batch", {
      typeVersion: "1.0.0",
      name: "Classify",
      config: {
        questions: {
          kind: {
            kind: "choice",
            instructions: "What kind of issue is this?",
            options: {
              bug: "Something is broken",
              feature: "New capability requested",
              docs: "Documentation problem",
              question: "Usage question",
            },
          },
          severity: {
            kind: "score",
            instructions: "How severe (bugs) or impactful (otherwise) is this?",
            levels: ["Trivial", "Minor", "Moderate", "Major", "Critical"],
          },
        },
      },
      inputs: {
        state: obj({
          title: ref("start", "issue", "/title"),
          body: expr("coalesce(start.issue.body, '')"),
        }),
      },
      credentials: { typesafe: "TYPESAFE_API_KEY" },
    }),
    similar: task("flowaid.retrieval.hybrid_search", {
      typeVersion: "1.0.0",
      name: "Similar issues",
      config: {
        sourceIds: ["$template.knowledge.github_issues"],
        mode: "hybrid",
        k: 5,
        filter: { state: "open" },
      },
      inputs: { query: tpl("{{ start.issue.title }}\n\n{{ start.issue.body }}") },
    }),
    dup_judge: task("flowaid.decision.boolean", {
      typeVersion: "1.0.0",
      name: "Duplicate of top candidate?",
      config: {
        instructions:
          "Is the new issue a duplicate of the top candidate (same root cause or same request)?",
        criteria: { true: "Duplicate", false: "Different problem despite similar words" },
      },
      inputs: {
        state: obj({ issue: ref("start", "issue"), candidate: expr("first(similar.hits)") }),
      },
      credentials: { typesafe: "TYPESAFE_API_KEY" },
    }),
    is_dup: branch("Duplicate?", {
      cases: [
        {
          port: "dup",
          when: "similar.count > 0 && dup_judge.decision.value && dup_judge.decision.confidence >= 0.8",
        },
      ],
      defaultPort: "new",
    }),
    gh_dup_comment: task("flowaid.tools.mcp", {
      typeVersion: "1.0.0",
      name: "Comment duplicate",
      config: { serverId: "00000000-0000-4000-8000-676974687562", tool: "add_issue_comment" },
      inputs: {
        owner: expr("split(start.repository.full_name, '/')[0]"),
        repo: expr("split(start.repository.full_name, '/')[1]"),
        issue_number: ref("start", "issue", "/number"),
        body: tpl(
          "Possible duplicate of #{{ first(similar.hits).metadata.number }} (confidence {{ round(dup_judge.decision.confidence, 2) }}).",
        ),
      },
      credentials: { mcp: "GITHUB_MCP" },
    }),
    labels: task("flowaid.data.transform", {
      typeVersion: "1.0.0",
      name: "Compute labels",
      config: {
        output: { type: "array", items: { type: "string" } },
        expr: "[classify.answers.kind.value, 'severity:' + lower(classify.answers.severity.levelLabel)]",
      },
    }),
    gh_label: task("flowaid.tools.mcp", {
      typeVersion: "1.0.0",
      name: "Apply labels",
      config: { serverId: "00000000-0000-4000-8000-676974687562", tool: "add_issue_labels" },
      inputs: {
        owner: expr("split(start.repository.full_name, '/')[0]"),
        repo: expr("split(start.repository.full_name, '/')[1]"),
        issue_number: ref("start", "issue", "/number"),
        labels: ref("labels", "result"),
      },
      credentials: { mcp: "GITHUB_MCP" },
      policy: {
        retry: {
          maxAttempts: 3,
          backoff: { type: "exponential", initialMs: 500, maxMs: 30000, factor: 2, jitter: true },
          allowOnIrreversible: false,
        },
        onError: "fail",
      },
    }),
    remember: task("flowaid.retrieval.upsert", {
      typeVersion: "1.0.0",
      name: "Index the issue",
      config: { sourceId: "$template.knowledge.github_issues" },
      inputs: {
        documents: arr([
          obj({
            externalId: tpl("{{ start.repository.full_name }}#{{ start.issue.number }}"),
            title: ref("start", "issue", "/title"),
            uri: ref("start", "issue", "/html_url"),
            mimeType: lit("text/markdown"),
            text: tpl("# {{ start.issue.title }}\n\n{{ start.issue.body }}"),
            metadata: obj({
              number: ref("start", "issue", "/number"),
              state: lit("open"),
              kind: ref("classify", "answers", "/kind/value"),
            }),
          }),
        ]),
      },
    }),
    route: branch("Route", {
      cases: [
        {
          port: "oncall",
          when: "classify.answers.kind.value == 'bug' && classify.answers.severity.value >= 3",
        },
        { port: "product", when: "classify.answers.kind.value == 'feature'" },
      ],
      defaultPort: "backlog",
    }),
    page: task("flowaid.tools.http", {
      typeVersion: "1.0.0",
      name: "Notify on-call",
      config: {
        method: "POST",
        url: "https://hooks.slack.com/services/T000/B000/XXXX",
        responseType: "json",
        body: {
          kind: "object",
          fields: {
            text: {
              kind: "template",
              source:
                ":rotating_light: Critical bug {{ start.issue.html_url }} (sev {{ round(classify.answers.severity.value, 1) }})",
            },
          },
        },
      },
    }),
    out_ignored: output("Ignored", {
      value: obj({ handled: lit(false), route: lit("ignored") }),
      outcome: "ignored",
    }),
    out_dup: output("Duplicate", {
      value: obj({
        handled: lit(true),
        duplicate_of: expr("first(similar.hits).metadata.number"),
        route: lit("duplicate"),
      }),
      outcome: "duplicate",
    }),
    out_routed: output("Routed", {
      value: obj({
        handled: lit(true),
        labels: ref("labels", "result"),
        route: expr("first(route.taken)"),
      }),
      outcome: "routed",
    }),
  },
  edges: [
    edge({ node: "opened", port: "no" }, "out_ignored", "c1"),
    edge({ node: "opened", port: "yes" }, "actionable", "c2"),
    edge({ node: "act_gate", port: "no" }, "out_ignored", "c3"),
    edge({ node: "act_gate", port: "yes" }, "classify", "c4"),
    edge({ node: "act_gate", port: "yes" }, "similar", "c5"),
    edge({ node: "is_dup", port: "dup" }, "gh_dup_comment", "c6"),
    edge({ node: "gh_dup_comment", port: "done" }, "out_dup", "c7"),
    edge({ node: "is_dup", port: "new" }, "labels", "c8"),
    edge({ node: "labels", port: "done" }, "gh_label", "c9"),
    edge({ node: "gh_label", port: "done" }, "remember", "c_remember_in"),
    edge({ node: "remember", port: "done" }, "route", "c_remember_out"),
    edge({ node: "route", port: "oncall" }, "page", "c11"),
    edge({ node: "page", port: "done" }, "out_routed", "c12"),
    edge({ node: "route", port: "product" }, "out_routed", "c13"),
    edge({ node: "route", port: "backlog" }, "out_routed", "c14"),
  ],
  layout: {
    nodes: {
      start: { x: 0, y: 220 },
      opened: { x: 260, y: 220 },
      actionable: { x: 520, y: 220 },
      act_gate: { x: 780, y: 220 },
      classify: { x: 1040, y: 220 },
      similar: { x: 1300, y: 220 },
      dup_judge: { x: 1560, y: 220 },
      is_dup: { x: 1820, y: 220 },
      gh_dup_comment: { x: 2080, y: 220 },
      labels: { x: 2340, y: 220 },
      gh_label: { x: 2600, y: 220 },
      route: { x: 2860, y: 220 },
      page: { x: 3120, y: 220 },
      out_ignored: { x: 3380, y: 220 },
      out_dup: { x: 3640, y: 220 },
      out_routed: { x: 3900, y: 220 },
      remember: { x: 2730, y: 400 },
    },
  },
});

export default workflow;
