/**
 * The failure-mode catalog as data (JEV_ENGINEERING.md §13.1, handbook §X, Table IX).
 *
 * Rows 1–12 are §X.A–§X.L; rows 13–31 are the warnings of other sections. "Static" are the
 * compiler/critic diagnostics, "runtime" the route reasons or receipt checks, "review" the
 * TraceReviewer signals, "inspectFirst" follows Table IX. Compiler diagnostics, runtime route
 * reasons, TraceReviewer signals and advisor rules all come from this one catalog (rule R10).
 */
import type { RouteReason } from "../wire.js";
import type { JevDiagnosticCode } from "./codes.js";

/** One failure mode. */
export interface FailureMode {
  /** 1..31 (§13.1 row number). */
  id: number;
  title: string;
  /** Handbook section, e.g. "§X.A". */
  handbook: string;
  /** Diagnostic codes that detect it statically. */
  static: readonly JevDiagnosticCode[];
  /** Prose for static detection that is not a code (by construction, schema, tests). */
  staticNote: string | null;
  /** Route reasons (or receipt checks) that surface it at run time. */
  runtime: readonly RouteReason[];
  runtimeNote: string | null;
  /** TraceReviewer signals / drift alarms. */
  review: readonly string[];
  /** Table IX "inspect first". */
  inspectFirst: readonly string[];
  correction: string;
}

const row = (
  id: number,
  title: string,
  handbook: string,
  staticCodes: readonly JevDiagnosticCode[],
  staticNote: string | null,
  runtime: readonly RouteReason[],
  runtimeNote: string | null,
  review: readonly string[],
  inspectFirst: readonly string[],
  correction: string,
): FailureMode =>
  Object.freeze({
    id,
    title,
    handbook,
    static: staticCodes,
    staticNote,
    runtime,
    runtimeNote,
    review,
    inspectFirst,
    correction,
  });

/** The 31-row catalog of §13.1. */
export const FAILURE_MODES: readonly FailureMode[] = Object.freeze([
  row(
    1,
    "Conclusions stored as evidence",
    "§X.A",
    ["W_JEV_CONCLUSION_AS_EVIDENCE", "I_JEV_INHERITED_JUDGMENT"],
    null,
    [],
    null,
    ["override_on_auto"],
    ["evidence"],
    "Observable evidence: source count and type, verified/unresolved claims, freshness",
  ),
  row(
    2,
    "No escape hatch",
    "§X.B",
    ["W_JEV_NO_ESCAPE_HATCH", "E_JEV_DYNAMIC_MENU_NO_ESCAPE"],
    null,
    [],
    "escape rate 0 with overrides",
    ["override_on_auto"],
    ["menu completeness"],
    "Add none/other/stop/review",
  ),
  row(
    3,
    "One threshold for every consequence",
    "§X.C",
    ["W_JEV_SINGLE_THRESHOLD", "W_JEV_THRESHOLDS_ILLUSTRATIVE"],
    null,
    ["consequence_irreversible"],
    null,
    ["unsafe_action"],
    ["authority boundary", "policy order"],
    "Per-class thresholds; irreversible review-gated",
  ),
  row(
    4,
    "Stale options",
    "§X.D",
    ["W_JEV_EVIDENCE_UNVERSIONED"],
    null,
    ["stale_option", "stale_evidence"],
    "action failure stale_option",
    ["stale_choice"],
    ["state freshness"],
    "Rebuild from live state; version every decision",
  ),
  row(
    5,
    "Blind retries",
    "§X.E",
    ["E_JEV_BLIND_RETRY", "W_JEV_IMPROVE_UNWIRED"],
    null,
    ["blind_retry_blocked", "improve_budget_exhausted"],
    null,
    ["repeated_loop"],
    ["stop option", "retry evidence"],
    "Each retry adds evidence, changes the contract, narrows the menu or escalates",
  ),
  row(
    6,
    "Winner-only logging",
    "§X.F",
    [],
    "by construction (receipts)",
    [],
    "reconstruction step 4 fails",
    ["partially_observable_decision"],
    [],
    "Complete receipt",
  ),
  row(
    7,
    "Policy inside the classifier",
    "§X.G",
    ["W_JEV_POLICY_IN_CLASSIFIER", "E_JEV_AUTHORITY_EXCEEDED", "E_JEV_IRREVERSIBLE_AUTO"],
    null,
    [],
    "policy record",
    ["unsafe_action"],
    ["authority boundary", "policy order"],
    "Permissions, budgets, scopes, side effects in deterministic policy",
  ),
  row(
    8,
    "Exact rules delegated to Jev",
    "§X.H",
    ["W_JEV_EXACT_RULE"],
    null,
    [],
    null,
    [],
    ["criteria"],
    "Code (`branch`, FlowExpr)",
  ),
  row(
    9,
    "Unknown values hidden inside a label",
    "§X.I Unknown Values",
    ["W_JEV_FREE_VALUE"],
    null,
    [],
    null,
    [],
    ["criteria"],
    "Extraction/generation, then Jev over the known set",
  ),
  row(
    10,
    "Multi-step plan in one answer",
    "§X.J",
    ["W_JEV_OPTIONS_UNDISTINGUISHED"],
    "multi-step descriptions",
    [],
    null,
    [],
    ["contract wording"],
    "Tool creates evidence → new snapshot → next contract",
  ),
  row(
    11,
    "Verifier checks transport success",
    "§X.K",
    ["W_JEV_TRANSPORT_VERIFICATION"],
    null,
    [],
    null,
    [],
    ["artifact checks"],
    "`flowaid.jev.verify` over new evidence",
  ),
  row(
    12,
    "Contract change without evaluation",
    "§X.L",
    ["W_JEV_CONTRACT_UNREVIEWED"],
    "review gate (§4.6)",
    [],
    null,
    [],
    [],
    "Version, replay history, shadow, rollback",
  ),
  row(
    13,
    "Transcript as state",
    "§IV.A",
    ["W_JEV_TRANSCRIPT_STATE"],
    null,
    ["packet_over_budget"],
    null,
    [],
    ["evidence"],
    "Compact packet",
  ),
  row(
    14,
    "Over-privileged state",
    "§IV.C",
    ["W_JEV_PACKET_UNDECLARED_FIELD", "E_JEV_PACKET_DATA_CLASS"],
    null,
    [],
    "secret_value failure",
    [],
    [],
    "Declared fields, eligibility",
  ),
  row(
    15,
    "Early flattening",
    "§V.A",
    ["W_JEV_CONFIDENCE_UNUSED"],
    null,
    [],
    null,
    [],
    [],
    "Route on the distribution",
  ),
  row(
    16,
    "Decorative confidence",
    "§V.B",
    ["W_JEV_IMPROVE_UNWIRED"],
    null,
    ["improve_budget_exhausted"],
    null,
    [],
    [],
    "Name the state-improving action",
  ),
  row(
    17,
    "Demo-set thresholds become policy",
    "§V.C",
    ["W_JEV_THRESHOLDS_ILLUSTRATIVE"],
    "protected deploy refused",
    ["thresholds_illustrative"],
    null,
    [],
    ["calibration"],
    "Governance record",
  ),
  row(
    18,
    "Global-average calibration",
    "§V.D",
    [],
    null,
    [],
    "segmentation by construction",
    [],
    ["calibration"],
    "Segment by version, class, language, option",
  ),
  row(
    19,
    "Stale calibration",
    "§V.F",
    [],
    null,
    ["model_version_changed"],
    "new segments per version",
    ["drift alarm"],
    ["calibration"],
    "Re-estimate after changes",
  ),
  row(
    20,
    "Dependent batching, mixed versions, evaluation after a write",
    "§VI.G",
    [],
    "structural (no dependency paths in bundles)",
    ["state_race"],
    null,
    ["partially_observable_decision"],
    ["state freshness"],
    "Snapshot discipline",
  ),
  row(
    21,
    "Mixed latency/privacy class batch",
    "§VI.D",
    ["E_JEV_BUNDLE_CLASS_MIX"],
    null,
    [],
    null,
    [],
    [],
    "Batch within one class",
  ),
  row(
    22,
    "Unlocked execution after parallel decisions",
    "§VI.F",
    ["W_JEV_PARALLEL_SIDE_EFFECTS"],
    null,
    [],
    null,
    [],
    ["execution"],
    "Serialize in the graph",
  ),
  row(
    23,
    "Risk judged from command names",
    "§VII.D",
    ["W_JEV_UNGATED_TOOL"],
    null,
    [],
    "tool-gate normalization",
    [],
    [],
    "Normalized proposal",
  ),
  row(
    24,
    "Jev at every edge / exact restatement / open-ended content",
    "§VII.F",
    ["W_JEV_PLACEMENT", "W_JEV_EXACT_RULE", "W_JEV_GENERATION_FOR_DECISION"],
    null,
    [],
    "route entropy ≈ 0 over 30 d",
    ["costs_rising"],
    ["wrong routes", "recovery work"],
    "Placement discipline",
  ),
  row(
    25,
    "Faulty menu builder blamed on Jev",
    "§VIII.D",
    [],
    "menu tests (§10.5)",
    [],
    "OPTION_SET_BUILT.counts, empty port",
    [],
    ["menu construction"],
    "Test the builder separately",
  ),
  row(
    26,
    "TTL-only cache",
    "§VIII.H",
    [],
    "E_CONFIG_INVALID (menu cache without invalidateOn)",
    [],
    null,
    [],
    [],
    "Event-driven invalidation",
  ),
  row(
    27,
    "Praise-style descriptions",
    "§VIII.F",
    ["W_JEV_OPTIONS_UNDISTINGUISHED"],
    null,
    [],
    null,
    ["label_disagreement"],
    ["contract wording"],
    "Evidence conditions; review/none on overlap",
  ),
  row(
    28,
    "No stop outcome",
    "§VIII.G",
    ["W_JEV_NO_STOP"],
    null,
    [],
    null,
    ["repeated_loop"],
    ["stop option"],
    "Declared stop",
  ),
  row(
    29,
    "Primitive mismatch",
    "§II.G",
    ["W_JEV_PRIMITIVE_MISMATCH"],
    null,
    [],
    null,
    [],
    ["criteria"],
    "Pick by answer shape; decompose",
  ),
  row(
    30,
    "Fake Score precision",
    "§II.B",
    ["W_JEV_SCORE_AS_MEASURE"],
    null,
    [],
    null,
    [],
    [],
    "Ordinal bands",
  ),
  row(
    31,
    "Guardrails depending on confidence",
    "§IX.I",
    [],
    "impossible by schema (RolloutGuardrailsSchema has no confidence input)",
    [],
    null,
    [],
    [],
    "Deterministic guardrails",
  ),
]);

/** flowaid-specific catalog entries that are not handbook rows (§13.1 "Related"). */
export const RELATED_FAILURE_CODES: Readonly<Record<string, readonly JevDiagnosticCode[]>> =
  Object.freeze({
    "generation used for a decision (§I.A)": ["W_JEV_GENERATION_FOR_DECISION"],
    "uncalibrated auto (conflict C3)": ["W_JEV_UNCALIBRATED_AUTO"],
    "consensus reassurance (conflict C6)": ["W_JEV_CONSENSUS_REASSURANCE"],
    "shadow isolation (§11.1)": ["E_JEV_SHADOW_LEAK"],
    "escalation (§9.5)": ["E_JEV_ESCALATION_UNWIRED"],
  });

/** Every catalog row a diagnostic code detects. */
export function failureModesForCode(code: JevDiagnosticCode): FailureMode[] {
  return FAILURE_MODES.filter((m) => m.static.includes(code));
}

/** Every catalog row a runtime route reason surfaces. */
export function failureModesForReason(reason: RouteReason): FailureMode[] {
  return FAILURE_MODES.filter((m) => m.runtime.includes(reason));
}

/** Table IX: observed symptom → what to inspect first (§X.M). */
export const OPERATIONAL_CORRECTIONS: Readonly<Record<string, readonly string[]>> = Object.freeze({
  "High confidence, wrong branch": ["evidence", "menu completeness", "calibration"],
  "Review rate rising": ["state freshness", "new option classes"],
  "Costs rising": ["wrong routes", "recovery work"],
  "Repeated loops": ["stop option", "retry evidence"],
  "Unsafe action": ["authority boundary", "policy order"],
  "Schema valid, meaning wrong": ["criteria", "representative tests"],
});
