import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import type { ReactNode } from "react";
import { afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import type { Diagnostic, WorkflowDefinition } from "@flowaid/workflow-core";
import { installDomStubs } from "@/primitives/testStubs";
import { blankDefinition } from "./model";
import { provenanceLine, remainingDiagnostics, type GeneratedWorkflow } from "./aiPlan";

vi.mock("next/navigation", () => ({
  usePathname: () => "/acme/workflows/new",
  useRouter: () => ({ push: vi.fn(), replace: vi.fn() }),
}));
vi.mock("~/session", () => ({
  useSession: () => ({
    ws: "acme",
    workspaceName: "Acme",
    features: { ai_builder: true, workflows: true },
    can: () => true,
  }),
}));
// the frame is covered on its own; here only the page body matters
vi.mock("~/shell/AppFrame", () => ({
  AppFrame: ({ children }: { children: ReactNode }) => children,
  PageBody: ({ children }: { children: ReactNode }) => children,
}));
const get = vi.hoisted(() => vi.fn());
const post = vi.hoisted(() => vi.fn());
vi.mock("~/api/client", async (actual) => ({
  ...(await actual<Record<string, unknown>>()),
  get,
  post,
}));

const { default: NewWorkflowPage } = await import("../../app/(app)/[ws]/workflows/new/page");

beforeAll(() => installDomStubs());
afterEach(() => {
  cleanup();
  get.mockReset();
  post.mockReset();
});

const ID = "3e7a1c9b-8d2f-4b6e-9a0c-5f4d3e2b1a09";
const def = (): WorkflowDefinition => blankDefinition(ID, "Refund triage");
const diag = (d: Partial<Diagnostic> & Pick<Diagnostic, "severity" | "message">): Diagnostic =>
  ({ code: "E_UNBOUND_INPUT", location: {}, ...d }) as Diagnostic;
const generated = (over: Partial<GeneratedWorkflow> = {}): GeneratedWorkflow => ({
  definition: def(),
  diagnostics: [],
  rationale: "Classify refunds and route them.",
  iterations: 2,
  model: { provider: "anthropic", model: "claude-x" },
  usage: { inputTokens: 900, outputTokens: 300 },
  costUsd: 0.004,
  ...over,
});

/** A promise the test settles by hand. */
function deferred<T>() {
  let resolve: (v: T) => void = () => undefined;
  const promise = new Promise<T>((r) => (resolve = r));
  return { promise, resolve };
}

describe("AI builder trust signals", () => {
  it("says who generated the plan, with tokens, cost and compile passes", () => {
    expect(provenanceLine(generated())).toBe(
      "Generated by anthropic/claude-x · 1.2k tokens · $0.00400 · 2 compile passes",
    );
    expect(provenanceLine(generated({ iterations: 1 }))).toContain("1 compile pass");
  });

  it("lists the remaining diagnostics, errors first, with node names", () => {
    const d = def();
    const out = remainingDiagnostics(
      [
        diag({ severity: "warning", message: "No failover" }),
        diag({ severity: "error", message: "Input not bound", location: { nodeId: "end" } }),
      ],
      d,
    );
    expect(out.map((x) => [x.severity, x.message, x.nodeName])).toEqual([
      ["error", "Input not bound", "End"],
      ["warning", "No failover", undefined],
    ]);
  });

  it("walks the page through generating, done and saving", async () => {
    get.mockResolvedValue([]);
    const generating = deferred<GeneratedWorkflow>();
    const saving = deferred<{ id: string }>();
    post.mockImplementation((path: string) =>
      path === "/v1/workflows/ai/generate" ? generating.promise : saving.promise,
    );
    const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
    render(
      <QueryClientProvider client={client}>
        <NewWorkflowPage />
      </QueryClientProvider>,
    );

    fireEvent.change(screen.getByRole("textbox", { name: "Describe the workflow" }), {
      target: { value: "Triage refunds" },
    });
    fireEvent.click(screen.getByRole("button", { name: "Generate plan" }));
    await screen.findByText("generating");
    expect(screen.queryByText("streaming")).toBeNull();

    await act(async () => {
      generating.resolve(
        generated({
          diagnostics: [diag({ severity: "error", message: "Input not bound" })],
        }),
      );
      await generating.promise;
    });
    await screen.findByText("plan ready");
    expect(screen.getByText(/Generated by anthropic\/claude-x · 1.2k tokens/)).toBeTruthy();
    const left = screen.getByText("Left to fix in the builder").closest("section");
    expect(left?.textContent).toContain("Input not bound");

    fireEvent.click(screen.getByRole("button", { name: "Apply to canvas" }));
    await screen.findByText("saving");
    expect(screen.getByRole("button", { name: /Saving/ }).getAttribute("aria-busy")).toBe("true");
    await act(async () => {
      saving.resolve({ id: "w1" });
      await saving.promise;
    });
    await waitFor(() => expect(post).toHaveBeenCalledTimes(2));
  });

  it("draws the keyboard focus ring of the hidden file input on its label", () => {
    get.mockResolvedValue([]);
    const client = new QueryClient();
    const { container } = render(
      <QueryClientProvider client={client}>
        <NewWorkflowPage />
      </QueryClientProvider>,
    );
    const input = container.querySelector('input[type="file"]');
    const label = input?.closest("label");
    expect(input?.className).toContain("sr-only");
    expect(label?.className).toContain("has-[:focus-visible]:shadow-(--focus)");
  });
});
