/**
 * PageIndex document sources in the web app (docs/pageindex/API.md): response shapes, the
 * processing disclosure, upload checks, index states and the source viewer's URL. Types come from
 * RFC-0022 (`@flowaid/workflow-core` documentIndex).
 */
import type {
  DocumentIndexState,
  DocumentReference,
  DocumentScope,
  Evidence,
  GroundedAnswer,
  IndexReference,
  OutlineNode,
  RetrievalResult,
} from "@flowaid/workflow-core";

export type {
  DocumentIndexState,
  DocumentReference,
  Evidence,
  GroundedAnswer,
  IndexReference,
  OutlineNode,
  RetrievalResult,
};

/** One document of a source (`GET /v1/pageindex/sources/:id/documents`). */
export interface DocumentSummary {
  documentId: string;
  title: string;
  status: string;
  versions: number;
  latestVersion: DocumentReference;
  activeIndex: IndexReference | null;
  latestIndex: IndexReference | null;
}

export interface UploadResult {
  document: DocumentSummary;
  version: DocumentReference;
  index: IndexReference;
  created: boolean;
}

export interface PageIndexStatus {
  enabled: boolean;
  reachable: boolean;
  sdkVersion: string | null;
  protocol: number | string | null;
}

export interface QueryRequest {
  query: string;
  scope: DocumentScope;
  answer?: boolean;
}

export interface QueryResponse {
  retrieval: RetrievalResult;
  answer: GroundedAnswer | null;
  model: { provider: string; model: string } | null;
}

/**
 * How documents are processed, copied from `MODES` in `@flowaid/pageindex` (capabilities.ts). The
 * web app may not import that package; keep these strings in step with it.
 */
export const PROCESSING = {
  local:
    "Files are parsed on the machine running the FlowAId PageIndex service. Section summaries are written by the indexing model you choose, so page text is sent to that model's provider (nothing leaves this machine when the model is Ollama here).",
  cloud:
    "PageIndex cloud (managed OCR, block-level citations) is not enabled in this release: it could not be verified without cloud credentials. Documents are never uploaded to it.",
} as const;

export const MODEL_DISCLOSURE = "Generated by a model; open the cited pages to verify.";

// ── the source's settings ──────────────────────────────────────────────────────────────────────

export type IndexProvider = "openai" | "anthropic" | "ollama";
export const INDEX_PROVIDERS: readonly IndexProvider[] = ["openai", "anthropic", "ollama"];
export type IndexMode = "flash" | "standard";
/** `off` (default) keeps the detected hierarchy; `merge` folds short sections; `full` also expands with the model */
export type IndexOptimize = "merge" | "full" | "off";

export const OPTIMIZE_LABEL: Record<IndexOptimize, string> = {
  off: "Keep sections (default)",
  merge: "Fold short sections",
  full: "Fold and expand with the model",
};

export interface PageIndexConfig {
  indexModel: { provider: IndexProvider; model: string };
  credentialId: string | null;
  mode: IndexMode;
  optimize: IndexOptimize;
}

/** A model to suggest when a provider is picked and the registry names none. */
export const DEFAULT_INDEX_MODEL: Record<IndexProvider, string> = {
  openai: "gpt-4.1-mini",
  anthropic: "claude-haiku-4-5",
  ollama: "qwen2.5:3b",
};

/** The credential type that holds a provider's key (Ollama: its host). */
export const credentialTypeOf = (p: IndexProvider): string =>
  p === "ollama" ? "ollama.host" : `${p}.api_key`;

export const isIndexProvider = (v: string): v is IndexProvider =>
  (INDEX_PROVIDERS as readonly string[]).includes(v);

/** The chat models of the registry an index can be built with, per provider. */
export function indexModelsOf(
  models: readonly { provider: string; model: string; kind: string; deprecated?: boolean }[],
  provider: IndexProvider,
): string[] {
  return models
    .filter(
      (m) =>
        m.provider === provider && (m.kind === "chat" || m.kind === "decision") && !m.deprecated,
    )
    .map((m) => m.model)
    .filter((m, i, all) => all.indexOf(m) === i);
}

/** A source's PageIndex settings, read defensively from its stored config. */
export function readConfig(config: Record<string, unknown>): PageIndexConfig | null {
  const m = config.indexModel;
  if (typeof m !== "object" || m === null) return null;
  const provider = "provider" in m && typeof m.provider === "string" ? m.provider : "";
  const model = "model" in m && typeof m.model === "string" ? m.model : "";
  if (!isIndexProvider(provider) || !model) return null;
  return {
    indexModel: { provider, model },
    credentialId: typeof config.credentialId === "string" ? config.credentialId : null,
    mode: config.mode === "standard" ? "standard" : "flash",
    optimize: config.optimize === "full" || config.optimize === "merge" ? config.optimize : "off",
  };
}

// ── uploads ────────────────────────────────────────────────────────────────────────────────────

export const MAX_PDF_BYTES = 50 * 1024 * 1024;

/** Why a picked file cannot be uploaded (null: it can). The server checks the bytes again. */
export function pdfFileError(file: { name: string; type: string; size: number }): string | null {
  const pdfName = /\.pdf$/i.test(file.name);
  const pdfType = file.type === "application/pdf";
  if (!pdfType && !(pdfName && (file.type === "" || file.type === "application/octet-stream")))
    return "Not a PDF. PageIndex reads PDF files only.";
  if (file.size === 0) return "The file is empty.";
  if (file.size > MAX_PDF_BYTES)
    return `Larger than 50 MiB (${formatBytes(file.size)}). Split or compress it first.`;
  return null;
}

export function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(0)} KiB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MiB`;
}

/** What an upload error means for the person (by the API's status and code). */
export function uploadErrorMessage(status: number, code: string, message: string): string {
  if (status === 415 || code === "UNSUPPORTED_MEDIA_TYPE")
    return "The server read this file and it is not a PDF.";
  if (status === 413 || code === "PAYLOAD_TOO_LARGE") return "Larger than the 50 MiB limit.";
  if (code === "PAGEINDEX_DISABLED") return "PageIndex is not configured on this server.";
  if (status === 503 || code === "PAGEINDEX_UNAVAILABLE")
    return "The PageIndex service did not answer. Try again once it is running.";
  return message;
}

// ── index states ───────────────────────────────────────────────────────────────────────────────

/** States in which the index is still changing (the list polls while any is). */
const IN_FLIGHT: ReadonlySet<DocumentIndexState> = new Set([
  "queued",
  "running",
  "cancel_requested",
]);

export const isInFlight = (s: DocumentIndexState | undefined): boolean =>
  s !== undefined && IN_FLIGHT.has(s);

/** A readable outline exists (ready, or superseded by a newer one that is still readable). */
export const isReadable = (s: DocumentIndexState | undefined): boolean =>
  s === "ready" || s === "superseded";

/** The index a row describes: the newest build, else the one serving reads. */
export const rowIndex = (d: DocumentSummary): IndexReference | null =>
  d.latestIndex ?? d.activeIndex;

/** The index whose outline and reads a row offers: the active one when it is readable. */
export function readableIndex(d: DocumentSummary): IndexReference | null {
  if (d.activeIndex && isReadable(d.activeIndex.state)) return d.activeIndex;
  if (d.latestIndex && isReadable(d.latestIndex.state)) return d.latestIndex;
  return null;
}

/** Poll every 3 s while any document's index is queued, running or being canceled. */
export function pollInterval(items: readonly DocumentSummary[] | undefined): number | false {
  return items?.some((d) => isInFlight(d.latestIndex?.state) || isInFlight(d.activeIndex?.state))
    ? 3000
    : false;
}

export const STATE_LABEL: Record<DocumentIndexState, string> = {
  queued: "Queued",
  running: "Indexing",
  ready: "Ready",
  failed: "Failed",
  cancel_requested: "Canceling",
  canceled: "Canceled",
  superseded: "Superseded",
  deleted: "Deleted",
};

export function stateTone(s: DocumentIndexState): "ok" | "danger" | "accent" | "warn" | "neutral" {
  if (s === "ready") return "ok";
  if (s === "failed") return "danger";
  if (s === "queued" || s === "running") return "accent";
  if (s === "cancel_requested" || s === "canceled") return "warn";
  return "neutral";
}

/**
 * What to do about a failed index. Local PageIndex reads the text layer only, so a scanned PDF
 * fails; say so instead of the backend's message.
 */
export function indexErrorHint(error: { code: string; message: string }): string {
  const text = `${error.code} ${error.message}`;
  if (/scann|no[_ -]?text|text[_ -]?layer|image[_ -]?only|\bocr\b/i.test(text))
    return "This PDF has no text layer (scanned). Run OCR first; local PageIndex does not OCR.";
  if (/encrypt|password/i.test(text))
    return "This PDF is password-protected. Remove the protection and upload it again.";
  if (/credential|api[_ -]?key|unauthori[sz]ed|\b401\b|\b403\b/i.test(text))
    return `The indexing model's provider refused the key: ${error.message}`;
  return error.message;
}

// ── the source viewer ──────────────────────────────────────────────────────────────────────────

/** The stored PDF of one document version. */
export const filePath = (documentId: string, versionId: string): string =>
  `/v1/pageindex/documents/${encodeURIComponent(documentId)}/versions/${encodeURIComponent(versionId)}/file`;

/** A physical page in the browser's PDF viewer (`#page=N`, 1-based). */
export const pageFragment = (page: number): string => `#page=${Math.max(1, Math.floor(page))}`;

export const pageSpan = (start: number, end: number): string =>
  end > start ? `pp. ${start}–${end}` : `p. ${start}`;

// ── answers ────────────────────────────────────────────────────────────────────────────────────

export type AnswerPart = { text: string } | { citation: number };

/**
 * The answer text cut at its citation markers: text runs and the index (into `citations`) of each
 * marker, so markers render as buttons. Markers the answer does not contain are left out.
 */
export function splitAnswer(
  answer: string,
  citations: readonly { marker: string }[],
): AnswerPart[] {
  const markers = citations
    .map((c, i) => ({ marker: c.marker, i }))
    .filter((m) => m.marker.length > 0)
    .sort((a, b) => b.marker.length - a.marker.length);
  const parts: AnswerPart[] = [];
  let run = "";
  let at = 0;
  while (at < answer.length) {
    const hit = markers.find((m) => answer.startsWith(m.marker, at));
    if (hit) {
      if (run) parts.push({ text: run });
      run = "";
      parts.push({ citation: hit.i });
      at += hit.marker.length;
    } else {
      run += answer[at];
      at += 1;
    }
  }
  if (run) parts.push({ text: run });
  return parts;
}
