/**
 * Generates the SDK and CLI surfaces from the API's OpenAPI 3.1 document (API.md §8):
 *
 * - `packages/workflow-sdk/openapi.json`: the document itself, built from `buildServer` with a
 *   stub context (route registration never touches the database);
 * - `packages/workflow-sdk/src/generated/openapi.ts`: `paths` types via openapi-typescript;
 * - `packages/cli/src/generated/operations.ts`: one entry per operation from its `x-cli`
 *   extension (noun, verb, positional path parameters), with query and body flags.
 *
 * Run with `pnpm sdk:types`; `--check` (in `pnpm check`) exits non-zero when a file is stale.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import * as prettier from "prettier";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SNAPSHOT = join(ROOT, "packages/workflow-sdk/openapi.json");
const TYPES = join(ROOT, "packages/workflow-sdk/src/generated/openapi.ts");
const OPERATIONS = join(ROOT, "packages/cli/src/generated/operations.ts");

type Json = Record<string, unknown>;
interface ApiModule {
  buildServer(
    ctx: unknown,
  ): Promise<{ ready(): Promise<unknown>; swagger(): unknown; close(): Promise<unknown> }>;
  defaultConfig(): unknown;
  AuthService: new (db: unknown, keys: unknown) => unknown;
  JwtKeys: { generate(): Promise<{ keys: unknown }> };
}

async function openApiDocument(): Promise<Json> {
  // A computed specifier keeps the API's sources out of the root typecheck.
  const api = (await import(join(ROOT, "apps/api/src/index.ts"))) as ApiModule;
  const keys = (await api.JwtKeys.generate()).keys;
  const unused = {};
  const app = await api.buildServer({
    config: api.defaultConfig(),
    db: unused,
    keys,
    auth: new api.AuthService(unused, keys),
    clock: { now: () => Date.now() },
    queue: unused,
    hub: unused,
    credentials: unused,
    http: unused,
  });
  await app.ready();
  const doc = structuredClone(app.swagger()) as Json;
  await app.close();
  return doc;
}

interface CliParam {
  name: string;
  type: string;
  required: boolean;
  enum?: unknown[];
  description?: string;
}

function schemaType(schema: Json | undefined): string {
  if (!schema) return "any";
  const t = schema.type;
  if (typeof t === "string") return t;
  if (Array.isArray(t)) return (t.find((x) => x !== "null") as string | undefined) ?? "any";
  return "any";
}

function param(
  name: string,
  schema: Json | undefined,
  required: boolean,
  description?: unknown,
): CliParam {
  const out: CliParam = { name, type: schemaType(schema), required };
  if (Array.isArray(schema?.enum)) out.enum = schema.enum as unknown[];
  const d = description ?? schema?.description;
  if (typeof d === "string") out.description = d;
  return out;
}

function cliOperations(doc: Json) {
  const ops = [];
  for (const [path, methods] of Object.entries(doc.paths as Record<string, Record<string, Json>>)) {
    for (const [method, op] of Object.entries(methods)) {
      const cli = op["x-cli"] as { noun: string; verb: string; positional?: string[] } | undefined;
      if (!cli) throw new Error(`${method.toUpperCase()} ${path} has no x-cli extension`);
      const parameters = (op.parameters ?? []) as Json[];
      const bodySchema = (op.requestBody as Json | undefined)?.content as
        Record<string, { schema?: Json }> | undefined;
      const body = bodySchema?.["application/json"]?.schema;
      const bodyRequired = new Set((body?.required as string[] | undefined) ?? []);
      ops.push({
        noun: cli.noun,
        verb: cli.verb,
        method: method.toUpperCase(),
        path,
        ...(typeof op.summary === "string" ? { summary: op.summary } : {}),
        auth: (op["x-auth"] as string | undefined) ?? "session_or_api_key",
        positional: cli.positional ?? [],
        query: parameters
          .filter((p) => p.in === "query")
          .map((p) =>
            param(p.name as string, p.schema as Json, p.required === true, p.description),
          ),
        body: body
          ? {
              required: (op.requestBody as Json).required === true,
              properties: Object.entries((body.properties ?? {}) as Record<string, Json>).map(
                ([name, s]) => param(name, s, bodyRequired.has(name)),
              ),
            }
          : null,
      });
    }
  }
  return ops.sort((a, b) => (a.noun + a.verb < b.noun + b.verb ? -1 : 1));
}

async function format(text: string, file: string): Promise<string> {
  const options = (await prettier.resolveConfig(file)) ?? {};
  return prettier.format(text, { ...options, filepath: file });
}

const doc = await openApiDocument();
const header =
  "// Generated by scripts/gen-sdk-types.ts from the API's OpenAPI document. Do not edit.\n";
const targets: { path: string; next: string }[] = [
  { path: SNAPSHOT, next: await format(JSON.stringify(doc), SNAPSHOT) },
  {
    path: TYPES,
    next: await format(
      `${header}/* eslint-disable */\n${astToString(await openapiTS(doc as never, { alphabetize: true }))}`,
      TYPES,
    ),
  },
  {
    path: OPERATIONS,
    next: await format(
      `${header}import type { CliOperation } from "../operation.js";\n\nexport const OPERATIONS: readonly CliOperation[] = ${JSON.stringify(cliOperations(doc))};\n`,
      OPERATIONS,
    ),
  },
];

const check = process.argv.includes("--check");
let stale = 0;
for (const { path, next } of targets) {
  let current = "";
  try {
    current = readFileSync(path, "utf8");
  } catch {
    // missing counts as stale
  }
  if (current === next) {
    console.log(`up to date  ${path}`);
    continue;
  }
  stale += 1;
  if (check) console.error(`stale       ${path} (run pnpm sdk:types)`);
  else {
    writeFileSync(path, next);
    console.log(`wrote       ${path}`);
  }
}
if (check && stale > 0) process.exit(1);
// Fastify keeps timers alive briefly after close; the work is done.
process.exit(0);
