import type { WorkflowTemplateView } from "./TemplateGallery";

/** Starter templates shipped with the builder. Node lists are the MiniGraph shape (id, category, name). */
export const BUILDER_SAMPLE_TEMPLATES: WorkflowTemplateView[] = [
  {
    id: "typesafe-support-router",
    name: "TypeSafe Support Router",
    description:
      "Classify inbound tickets by intent and urgency with TypeSafe decisions, route by confidence and hold low-confidence cases for review.",
    categories: ["decision", "flow", "human", "safety"],
    decisionCount: 3,
    tags: ["support", "triage", "routing", "confidence gate"],
    nodes: [
      { id: "start", category: "flow", name: "Ticket received" },
      { id: "pii", category: "safety", name: "PII guard" },
      { id: "intent", category: "decision", name: "Intent" },
      { id: "urgency", category: "decision", name: "Urgency" },
      { id: "escalate", category: "decision", name: "Escalate?" },
      { id: "router", category: "flow", name: "Router" },
      { id: "reply", category: "generation", name: "Draft reply" },
      { id: "review", category: "human", name: "Agent review" },
      { id: "end", category: "flow", name: "Resolved" },
    ],
    edges: [
      { source: "start", target: "pii" },
      { source: "pii", target: "intent" },
      { source: "intent", target: "urgency" },
      { source: "urgency", target: "escalate" },
      { source: "escalate", target: "router" },
      { source: "router", target: "reply" },
      { source: "router", target: "review" },
      { source: "reply", target: "end" },
      { source: "review", target: "end" },
    ],
  },
  {
    id: "research-agent",
    name: "Research Agent",
    description:
      "Bounded research loop: plan queries, search and read with tools, score source relevance, and stop when coverage is sufficient.",
    categories: ["agent", "tool", "retrieval", "decision"],
    decisionCount: 2,
    tags: ["research", "loop", "search", "summarise"],
    nodes: [
      { id: "start", category: "flow", name: "Question" },
      { id: "plan", category: "agent", name: "Planner" },
      { id: "search", category: "tool", name: "Web search" },
      { id: "read", category: "tool", name: "Fetch page" },
      { id: "relevant", category: "decision", name: "Relevant?" },
      { id: "store", category: "retrieval", name: "Notes index" },
      { id: "enough", category: "decision", name: "Coverage" },
      { id: "write", category: "generation", name: "Write brief" },
      { id: "end", category: "flow", name: "Brief" },
    ],
    edges: [
      { source: "start", target: "plan" },
      { source: "plan", target: "search" },
      { source: "search", target: "read" },
      { source: "read", target: "relevant" },
      { source: "relevant", target: "store" },
      { source: "store", target: "enough" },
      { source: "enough", target: "plan" },
      { source: "enough", target: "write" },
      { source: "write", target: "end" },
    ],
  },
  {
    id: "document-processing",
    name: "Document Processing",
    description:
      "Load PDFs, split and embed them, extract structured fields with a schema, score extraction confidence and queue uncertain documents for a person.",
    categories: ["retrieval", "data", "decision", "human"],
    decisionCount: 1,
    tags: ["pdf", "extraction", "ocr", "embeddings"],
    nodes: [
      { id: "start", category: "flow", name: "File uploaded" },
      { id: "load", category: "retrieval", name: "PDF loader" },
      { id: "split", category: "data", name: "Chunk" },
      { id: "embed", category: "retrieval", name: "Embed" },
      { id: "extract", category: "generation", name: "Extract fields" },
      { id: "validate", category: "data", name: "Validate schema" },
      { id: "conf", category: "decision", name: "Extraction ok?" },
      { id: "review", category: "human", name: "Verify fields" },
      { id: "store", category: "state", name: "Save record" },
    ],
    edges: [
      { source: "start", target: "load" },
      { source: "load", target: "split" },
      { source: "split", target: "embed" },
      { source: "embed", target: "extract" },
      { source: "extract", target: "validate" },
      { source: "validate", target: "conf" },
      { source: "conf", target: "store" },
      { source: "conf", target: "review" },
      { source: "review", target: "store" },
    ],
  },
  {
    id: "agent-supervisor",
    name: "Agent Supervisor",
    description:
      "A supervisor agent delegates to specialised workers, checks each result with a TypeSafe score and retries or escalates on low quality.",
    categories: ["agent", "decision", "flow", "human"],
    decisionCount: 2,
    tags: ["multi-agent", "delegation", "supervisor", "workers"],
    nodes: [
      { id: "start", category: "flow", name: "Task" },
      { id: "sup", category: "agent", name: "Supervisor" },
      { id: "w1", category: "agent", name: "Coder" },
      { id: "w2", category: "agent", name: "Analyst" },
      { id: "w3", category: "agent", name: "Writer" },
      { id: "quality", category: "decision", name: "Quality score" },
      { id: "done", category: "decision", name: "Done?" },
      { id: "esc", category: "human", name: "Escalate" },
      { id: "end", category: "flow", name: "Deliver" },
    ],
    edges: [
      { source: "start", target: "sup" },
      { source: "sup", target: "w1" },
      { source: "sup", target: "w2" },
      { source: "sup", target: "w3" },
      { source: "w1", target: "quality" },
      { source: "w2", target: "quality" },
      { source: "w3", target: "quality" },
      { source: "quality", target: "done" },
      { source: "done", target: "sup" },
      { source: "done", target: "esc" },
      { source: "done", target: "end" },
    ],
  },
  {
    id: "github-issue-triage",
    name: "GitHub Issue Triage",
    description:
      "On a new issue: detect duplicates against the index, classify type and area, label and assign automatically above the threshold, otherwise comment for a maintainer.",
    categories: ["tool", "decision", "retrieval", "developer"],
    decisionCount: 3,
    tags: ["github", "labels", "duplicates", "webhook"],
    nodes: [
      { id: "start", category: "flow", name: "Issue opened" },
      { id: "fetch", category: "tool", name: "GitHub API" },
      { id: "dupe", category: "retrieval", name: "Similar issues" },
      { id: "isdupe", category: "decision", name: "Duplicate?" },
      { id: "type", category: "decision", name: "Issue type" },
      { id: "area", category: "decision", name: "Area" },
      { id: "label", category: "tool", name: "Apply labels" },
      { id: "comment", category: "tool", name: "Comment" },
      { id: "log", category: "developer", name: "Audit log" },
    ],
    edges: [
      { source: "start", target: "fetch" },
      { source: "fetch", target: "dupe" },
      { source: "dupe", target: "isdupe" },
      { source: "isdupe", target: "comment" },
      { source: "isdupe", target: "type" },
      { source: "type", target: "area" },
      { source: "area", target: "label" },
      { source: "label", target: "log" },
      { source: "comment", target: "log" },
    ],
  },
];
