/**
 * `@flowaid/nodes-core/manifest`: the core node manifests as data, without loading any executor, for
 * the API and docs (which may read manifests but not run nodes). Generated by `scripts/build-manifest.ts`.
 */
import type { NodeManifest } from "@flowaid/workflow-core";
import file from "../manifest.json" with { type: "json" };

export const coreManifests: readonly NodeManifest[] = (file as unknown as { nodes: NodeManifest[] })
  .nodes;
export const coreManifestPackage = { name: file.package, version: file.version };
